version: '3.8'

services:
  auth-rabbit:
    ports:
      - "5673:5672" # we forward this port because it's useful for debugging
      - "15673:15672" # here, we can access rabbitmq management plugin

  auth-redis:
    ports:
      - "6380:6379"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS

  auth-nginx:
    ports:
      - "10082:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./shared_volumes/static:/usr/share/nginx/djangodocker/static:ro
      - ./shared_volumes/media:/usr/share/nginx/djangodocker/media:ro

  auth-backend:
    image: 926080010171.dkr.ecr.ap-southeast-1.amazonaws.com/ric_auth_backend:dev-latest
    volumes:
      - ./:/app
      - ./shared_volumes/static:/mnt/shared_volumes/static:rw
      - ./shared_volumes/media:/mnt/shared_volumes/media:rw

  auth-celery:
    image: 926080010171.dkr.ecr.ap-southeast-1.amazonaws.com/ric_auth_backend:dev-latest
    volumes:
      - ./:/app

  auth-celery-beat:
    image: 926080010171.dkr.ecr.ap-southeast-1.amazonaws.com/ric_auth_backend:dev-latest
    volumes:
      - ./:/app  

networks:
  ric:
    name: ric
    driver: bridge
