# Generated by Django 3.1.1 on 2020-09-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(help_text='companies usually have a code for the group', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='hierarchy',
            field=models.PositiveSmallIntegerField(help_text='which level the group is in. With the top level group being 1. For easy reference only, should be calculated from parent_group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='name of the group', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(help_text='which organization this group belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='profiles.organization'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, help_text='The parent group. None if this is the top level group', null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.group'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='name of the organization/company', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(editable=False, help_text='a unique, URL ready name of the organization name', max_length=100, unique=True),
        ),
    ]
