# Generated by Django 3.1.1 on 2020-10-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(help_text='User avatar. Response will be full URL', null=True, upload_to='user_avatars/%Y/%m/%d/'),
        ),
    ]
