# Generated by Django 3.1.1 on 2020-11-05 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(help_text='A short description of the user, provided by the user themselves', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hiragana_name',
            field=models.CharField(help_text='Hiragana name in Japanese', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='katakana_name',
            field=models.CharField(help_text='Katakana name in Japanese', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(help_text='Which organization (client company) the user belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='profiles.organization'),
        ),
    ]
