# Generated by Django 3.1.1 on 2020-11-18 12:03

from django.db import migrations, models
import profiles.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201105_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(help_text='User avatar. Response will be full URL', null=True, upload_to=profiles.helpers.static_image_path_for_avatar),
        ),
    ]
