# Generated by Django 3.1.3 on 2020-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201118_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_counter',
            field=models.IntegerField(default=0, help_text='Number of times user has logged in.'),
        ),
    ]
