# Generated by Django 3.1.3 on 2021-01-25 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_emailreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrouprole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='profiles.group'),
        ),
        migrations.AlterField(
            model_name='usergrouprole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
