# Generated by Django 3.1.3 on 2021-01-28 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_add_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, help_text='The parent group. None if this is the top level group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_groups', to='profiles.group'),
        ),
    ]
