# Generated by Django 3.1.3 on 2021-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_customuser_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreset',
            name='fail_attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
